const STATES = [
		{ "state" : "Florida" ,"facebookStateID" :3852},
		{ "state" : "Connecticut", "facebookStateID": 3849},
		{ "state" : "Maine", "facebookStateID": 3862},
		{ "state" : "Massachusetts", "facebookStateID" : 3864 },
		{ "state" : "New Hampshire", "facebookStateID" :3872 },
		{ "state" : "Rhode Island", "facebookStateID" : 3882}, 
		{ "state" : "Vermont", "facebookStateID" : 3888},
		{ "state" : "New Jersey", "facebookStateID" : 3873},
		{ "state" : "New York", "facebookStateID" : 3875},
		{ "state" : "Pennsylvania", "facebookStateID" : 3881},
		{ "state" : "Illinois", "facebookStateID" : 3856},
		{ "state" : "Indiana", "facebookStateID" : 3857},
		{ "state" : "Michigan", "facebookStateID" : 3865},
		{ "state" : "Ohio", "facebookStateID" : 3878},
		{ "state" : "Wisconsin", "facebookStateID" : 3892},
		{ "state" : "Iowa", "facebookStateID" : 3858},
		{ "state" : "Kansas", "facebookStateID" : 3859},
		{ "state" : "Minnesota", "facebookStateID" : 3866},
		{ "state" : "Missouri", "facebookStateID" : 3868},
		{ "state" : "Nebraska", "facebookStateID" : 3870},
		{ "state" : "North Dakota", "facebookStateID" : 3877},
		{ "state" : "Colorado", "facebookStateID" : 3848},
		{ "state" : "South Dakota", "facebookStateID" : 3884},
		{ "state" : "Delaware", "facebookStateID" : 3850},
		{ "state" : "Georgia", "facebookStateID": 3853},
		{ "state" : "Maryland", "facebookStateID" : 3863},
		{ "state" : "North Carolina", "facebookStateID" : 3876},
		{ "state" : "South Carolina", "facebookStateID": 3883},
		{ "state" : "Virginia", "facebookStateID": 3889},
		{ "state" : "West Virginia", "facebookStateID": 3891},
		{ "state" : "Alabama", "facebookStateID": 3843},
		{ "state" : "Kentucky", "facebookStateID" : 3860},
		{ "state" : "Mississippi", "facebookStateID" : 3867},
		{ "state" : "Tennessee", "facebookStateID": 3885},
		{ "state" : "Arkansas", "facebookStateID": 3846},
		{ "state" : "Louisiana", "facebookStateID" : 3861},
		{ "state" : "Oklahoma", "facebookStateID" :  3879},
		{ "state" : "Texas", "facebookStateID" : 3886},
		{ "state" : "Arizona", "facebookStateID" : 3845},
		{ "state" : "Idaho", "facebookStateID": 3855},
		{ "state" : "Montana", "facebookStateID": 3869},
		{ "state" : "Nevada", "facebookStateID" : 3871},
		{ "state" : "New Mexico", "facebookStateID" : 3874},
		{ "state" : "Utah", "facebookStateID" : 3887},
		{ "state" : "Wyoming", "facebookStateID": 3893},
		{ "state" : "Alaska", "facebookStateID" : 3844},
		{ "state" : "California", "facebookStateID" : 3847},
		{ "state" : "Hawaii", "facebookStateID": 3854},
		{ "state" : "Oregon", "facebookStateID": 3880},
		{ "state" : "Washington", "facebookStateID" : 3890}
]

export default  STATES;